import profile from "../assets/images/profile.png";
import siren from "../assets/images/siren.png";
import thumbnail from "../assets/images/thumbnail.png";
import cards from "../assets/images/cards.png";
import path from "../assets/images/path.png";
import SERTlogo from "../assets/images/SERT-logo.png";
import logo from "../assets/images/logo.png";
import logoSmall from "../assets/images/logo-small.png";
import empty from "../assets/images/empty.png";
import emergencyResponse from "../assets/images/emergencyResponse.png";
import firstAid from "../assets/images/firstAid.jpg";
import naturalDisaster from "../assets/images/naturalDisaster.png";
import waterSafety from "../assets/images/waterSafety.jpg";
import charldrinBello from "../assets/images/charldrinBello.jpg";
import SERTpicture from "../assets/images/SERTpicture.png";
import kobyMacale from "../assets/images/kobyMacale.jpg";
import kiokiSerrano from "../assets/images/kiokiSerrano.jpg";
import luisMagdangal from "../assets/images/luisMagdangal.jpg";
import emergencyResponseHeader from "../assets/images/emergencyResponseHeader.png";
import riskAssessment from "../assets/images/riskAssessment.jpg";

export default { profile, charldrinBello, kiokiSerrano, luisMagdangal, riskAssessment, emergencyResponseHeader, kobyMacale, SERTpicture, siren, thumbnail, cards, path, SERTlogo, logo, logoSmall, empty, emergencyResponse, firstAid, waterSafety, naturalDisaster };
